### ISSUE TITLE
[Feature Request] Plugin Dependencies

### ISSUE THREAD

**Issue by TehcJS** [bridge-core/bridge.#18]
It would be nice to have Bridge install plugins that other plugins depend on so you don't have to copy and paste code from other plugins into your plugin if they are needed. This would also allow authors to be credited when a plugin depends on their plugin. You may define if you'd like your plugin to be a regular plugin, or a dependency plugin. An example of something you may need to depend on is the "``bridge.ui.common_window.js``" file. Easy way to add dependencies to a plugin: You could add an "``id``" property to plugins/dependencies so people would be able to access dependencies by just using the dependency id in this format: "``author.category.project``". If you'd like to access your own plugins and they're by you, then you may use them in your plugins.
Here's what an example plugin look like in the "``me.example.dependent_plugin.js``" file:
```js
Bridge.registerPlugin({
	author: "Me",
	version: "1.0.0",
	id: "me.example.dependent_plugin",
	name: "Dependent Plugin",
	description: "A plugin that depends on other plugins.",
	isDependency: false,
	dependencies: [ "bridge.ui.common_window" ]
});
```

**Comment by solvedDev** [comment]
Yes, so I definitely plan to bring better dependency support very soon but in a different format. I want to make plugins a folder instead of a single file with a manifest.json file defining the data ```Bridge.registerPlugin(...)``` is used for at the moment. The plugin API 2.0 (will be part of bridge. v1.0.0) also brings some significant internal advantages over the current implementation but it will be a breaking change for all currently existing plugins. The API change will hopefully also enable plugin creators to actually edit all the JSON file currently inside the "static" folder.

There's currently no timeline for these changes but v1.0.0 should be the next major bridge. version after v0.13.0.

**Comment by TehcJS** [comment]
I look forward to seeing this new feature! It would definitely help me out right now, as I am working on a bridge. plugin that depends on my other scripts. Good luck with v1.0.0.

**Comment by solvedDev** [comment]
Implemented by the option to include multiple scripts inside of a single plugin. Sharing data between scripts must be revisited
