### ISSUE TITLE
[BUG] Arrays are saved as {"0":"value","1":"value"} instead of ["value","value"]

### ISSUE THREAD

**Issue by dombomb64** [bridge-core/bridge.#230]
**Summary**
Sometimes, the program will keep saving arrays the wrong way for a specific file.

**To Reproduce**
1. Have a JSON file from a resource pack ready.
2. In bridge., create a new file with the same name and of the same type. (animation, render controller, etc.)
3. Close bridge.
4. Replace the new file with the other one.
5. Open bridge.
6. Open the file in bridge and choose "disk".
7. Make an edit, undo it, and save.

**Observed behavior**
Arrays are saved as objects with each value having a number assigned to it.
**Expected behavior**
Arrays are saved normally.

**Screenshots / File Attachments**
![Bridge Bug Screenshot](https://user-images.githubusercontent.com/49823019/87202900-81356380-c2cf-11ea-8c40-d1a2307fb9a9.png)

**Platform (please complete the following information):**
 - OS: Windows 10
 - App Version: 1.6.0

**Additional context**
This isn't how I first encountered this bug, but I don't know how that went, so I found another way to reproduce it. I actually intended the reproduction procedure to be a workaround so I could edit the file in bridge. XD

**Comment by solvedDev** [comment]
This is something that happens with animation files depending on their format. Minecraft's RP animations can take quite a few different shapes and we currently cannot support all of them. 

Thanks a lot for the very nice report but I believe that this issue might stay open for quite a while because there are currently a few more important issues that I have to work on :)

**Comment by solvedDev** [comment]
It is on our roadmap for the next couple of releases though!

**Comment by dombomb64** [comment]
Thank you!

> Minecraft's RP animations can take quite a few different shapes

Also, what do you mean by this?

**Comment by solvedDev** [comment]
Let's take your reproduction steps as an example: An object would actually also be totally valid there. It would be a timestamp object which determines how the bone moves over time.
This creates a problem because bridge. cannot know what your intention is when you write the file: Does the user want an object or an array?

**Comment by dombomb64** [comment]
Ah, okay. I see. Thanks again!
