### ISSUE TITLE
[Feature] Add Missing Vanilla Resources

### ISSUE THREAD

**Issue by DeeFeeCee** [bridge-core/bridge.#311]
**Summary**
Although there is a large amount of vanilla resources, they are not exhaustive. Some notable examples are in BP\recipes, wherein there is a lack of recipes utilizing planks (yet crimson & warped plank variants exist), beds, wooden buttons, chiseled & cut blocks (including in stonecutter), fireworks, furnace andesite, diorite, & granite into polished form, map variants (including expanded & locked), painting, shulker box variants, non-wood slabs, trapdoors, torch, & wool variants. Please add these in v2.

**Alternatives/Considerations**
Alternatively, have documentation for every way something can be crafted (e.g. using minecraft:wool to use any type of wool in a recipe & noting all the data values)

**Comment by solvedDev** [comment]
Thanks for your suggestion! 
We won't do this because we believe this is Minecraft's responsibility, not ours. 
The Minecraft team needs to provide a correct BP & RP for its vanilla gameplay and it should also provide better documentation.

If we start correcting Minecraft's mistakes, where do we stop? Should we start providing block behavior files for vanilla blocks which can already be created? Should we provide features & feature rules for vanilla structures?
That would all be way too much maintenance work for our small team
