### ISSUE TITLE
Windows and Norton saying there's a Virus

### ISSUE THREAD

**Issue by Axiocentarius** [bridge-core/bridge.#316]
Both my windows and Norton things are saying there's a trojan virus, and I don't think It can be trusted, if anyone can say why It's saying this then please do.

**Comment by solvedDev** [comment]
See: https://github.com/bridge-core/bridge./issues/148#issuecomment-581847684

This warning pops up because bridge. is distributed as an unsigned application. To add to the linked comment: If we would create a virus, do you think we would make it open source so anyone could see the malicious code?
We realize that this is very confusing to normal users though and that's why we are choosing a different distribution method for bridge. v2 which is in development right now and which does not give users this warning.
