### ISSUE TITLE
[BUG] Save and write files outside of MC workspace

### ISSUE THREAD

**Issue by ENDERZOMBI102** [bridge-core/bridge.#92]
**Summary**
with this "bug" the user can create files outside of the minecraft workdir, this can potentially create security issues, i can suggest to limit "../" to only 2, so an user can create files with this, but it can't actually create a file outside of mc workdir.

**To Reproduce**
1. create a file with ../../../../filename
2. create
3. the files was saved outside mc workdir

**Comment by elomina-spec** [comment]
Is this a robot message or by human? I would like to take a small amount of
your time to ask some questions regarding bridge and the minecraft packs,
thank you. I apologize for my english. I'm quite nervous asking you this. I
understand if you're not available. Still thank you and thank you for your
app.

**Comment by ENDERZOMBI102** [comment]
Like: what?

**Comment by elomina-spec** [comment]
1. How am I able to include functions on blocks like for crops and trees?

2. While I'm experimenting with the app. I suddenly was able to make logs
glow in the night. then I looked for the code or syntax (i don't know what
to call it) in the "lightning cache" then i saw the identifier the app
suggested to me "bridge:log" and it represented minecraft:log. There's a
directory path at the top of the code "BP/blocks/dirt.json" when I looked
for it, it's not there. I want to take a peek at the block behaviors that
minecraft  devs created themselves, so I can see how cactuses hurt you when
you get near enough or how the first question works.

3. There's a bug when you already opened the file then it overlapped the
tab bar, i can't reselect the overlapped tab so i have to open the file
from the tree view from the left, then boom the app would make a long
reload, i waited for a long time but it never stopped loading, so i closed
the app. Happens most of the time.I don't  know if this is a bug or my
laptop is slow but there's a time where it doesn't activate the bug and
there's a time it activates, unfortunately it happens when i'm in the
middle of something really complicated. I would suggest making the tabs
that overlapped have a button so I can re-open them without opening the
tree view of files on the left. I have so many files so i have to scroll
down again. It's very hard.

I guess this is for now. I know you're busy and you can answer whenever you
want, I will wait. But for me the app is amazing. It taught me so much
about making addons for minecraft. Keep up the goodwork. Thank you very
much for the app. Sorry If there's something you don't understand. i'm not
that quite good with english yet, but i will try to be more clear. Thank You

Noong Miy, Hun 24, 2020 nang 4:25 AM, sinulat ni ENDERZOMBI102 <
notifications@github.com> ang:
